version: '3.8'

services:
  eureka-server:
    build: Floreria/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - floreria-network

  api-gateway:
    build: Floreria/api-gateway
    container_name: api-gateway
    ports:
      - "8081:8081" # El puerto exigido en la rúbrica
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - floreria-network

  ms-productos:
    build: Floreria/ms-productos
    container_name: ms-productos
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - floreria-network

  ms-ventas:
    build: Floreria/ms-ventas
    container_name: ms-ventas
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - floreria-network

networks:
  floreria-network:
    driver: bridge